name: Playwright Docker Suite
on:
  workflow_dispatch: # 

jobs:
  docker-execution:
    name: "Run All Tests in Docker"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t playwright-tests .

    - name: Run Tests in Docker
      run: |
        docker run --rm \
        --shm-size=2gb \
        -v ${{ github.workspace }}/allure-results:/app/allure-results \
        -e API_URL=${{ vars.API_URL }} \
        -e API_ADMIN_TOKEN=${{ secrets.API_ADMIN_TOKEN }} \
        -e BASE_URL=${{ vars.BASE_URL }} \
        -e ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }} \
        -e ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }} \
        playwright-tests npx playwright test

    - name: Archive Allure Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results-docker
        path: allure-results/
        retention-days: 1